spring:
  profiles:
    active: local
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  shutdown: graceful
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

springdoc:
  swagger-ui:
    path: /swagger-ui.html

swagger:
  server:
    local: http://localhost:8080/api
    dev: https://dev.unibusk.site/api
    prod: https://unibusk.site/api

jwt:
  expiration-time:
    access-token: 3600
    refresh-token: 1209600

image-upload:
  presigned-url-expiration-minutes: 15
  local-root: ./build/local-image-uploads
